<nav>
    <ul>
        <li><a href="#" class="nav-tab nav-tab-active" id="nav-tab_areas" data-tab="areastable" title="Areas">Areas</a></li>
        <li><a href="#" class="nav-tab" id="nav-tab_calorific-data" data-tab="calorificdatatable" title="Calorific Data">Calorific Data Items</a></li>
        <li><a href="#" class="nav-tab" id="nav-tab_import-log-table" data-tab="importlogtable" title="Import Log">Import Log</a></li>
    </ul>
</nav>