<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="Content-Language" content="EN">
    <meta name="MobileOptimized" content="width"/>
    <meta name="HandheldFriendly" content="true"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <meta name="keywords" content="<?= $this->pageDataItems['meta_keywords'] ?>"/>
    <meta name="description" content="<?= $this->pageDataItems['meta_description'] ?>"/>
    <meta name="author" content="Charles Edwards"/>
    <meta name="robots" content="noindex,nofollow"/>
    <title><?= $this->pageDataItems['page_title'] ?></title>
    <link rel="stylesheet" href="/css/default.css"/>
</head>
<body>
<div id="container-wrapper">
    <header>
        <h1>Calorific Value Data Viewer</h1>
    </header>
    <main>